--- #YAML:1.0
name:               Catalyst-View-Tenjin
version:            0.041
abstract:           Tenjin view class for Catalyst.
author:
    - Ido Perlmuter <ido@ido50.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:     5.7
    Data::Dump:   0
    MRO::Compat:  0
    Tenjin:       0.061
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
